/*jslint */
/*global AdobeEdge: false, window: false, document: false, console:false, alert: false */
(function (compId) {

    "use strict";
    var im='images/',
        aud='media/',
        vid='media/',
        js='js/',
        fonts = {
        },
        opts = {
            'gAudioPreloadPreference': 'auto',
            'gVideoPreloadPreference': 'auto'
        },
        resources = [
        ],
        scripts = [
        ],
        symbols = {
            "stage": {
                version: "6.0.0",
                minimumCompatibleVersion: "5.0.0",
                build: "6.0.0.400",
                scaleToFit: "none",
                centerStage: "none",
                resizeInstances: false,
                content: {
                    dom: [
                        {
                            id: 'grey-background12',
                            type: 'image',
                            rect: ['0%', '0%', '100%', '100%', 'auto', 'auto'],
                            fill: ["rgba(0,0,0,0)",im+"grey-background1.jpg",'0px','0px']
                        },
                        {
                            id: 'text',
                            type: 'image',
                            rect: ['21%', '55%', '61%', '45%', 'auto', 'auto'],
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"text.png",'0px','0px']
                        },
                        {
                            id: 'banner-com-o-logotipo-do-twitter2',
                            type: 'image',
                            rect: ['3.1%', '60%', '26.4%', '31.7%', 'auto', 'auto'],
                            cursor: 'pointer',
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"banner-com-o-logotipo-do-twitter.png",'0px','0px']
                        },
                        {
                            id: 'youtube-logo2',
                            type: 'image',
                            rect: ['70.2%', '60%', '26.4%', '31.7%', 'auto', 'auto'],
                            cursor: 'pointer',
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"youtube-logo.png",'0px','0px']
                        },
                        {
                            id: 'new-facebook-logo-2015-400x4002',
                            type: 'image',
                            rect: ['36.9%', '60%', '26.4%', '31.7%', 'auto', 'auto'],
                            cursor: 'pointer',
                            opacity: '0',
                            fill: ["rgba(0,0,0,0)",im+"new-facebook-logo-2015-400x4002.png",'0px','0px']
                        }
                    ],
                    style: {
                        '${Stage}': {
                            isStage: true,
                            rect: ['null', 'null', '100%', '100%', 'auto', 'auto'],
                            overflow: 'hidden',
                            fill: ["rgba(255,255,255,1)"]
                        }
                    }
                },
                timeline: {
                    duration: 36954,
                    autoPlay: true,
                    data: [
                        [
                            "eid4",
                            "opacity",
                            1250,
                            760,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid29",
                            "height",
                            5000,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid35",
                            "height",
                            6000,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid41",
                            "height",
                            7000,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid82",
                            "height",
                            8000,
                            987,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid135",
                            "height",
                            8987,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid136",
                            "height",
                            9987,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid137",
                            "height",
                            10987,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid138",
                            "height",
                            11987,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid315",
                            "height",
                            12987,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid316",
                            "height",
                            13987,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid317",
                            "height",
                            14987,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid318",
                            "height",
                            15987,
                            987,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid319",
                            "height",
                            16974,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid320",
                            "height",
                            17974,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid321",
                            "height",
                            18974,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid322",
                            "height",
                            19974,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid331",
                            "height",
                            20974,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid332",
                            "height",
                            21974,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid333",
                            "height",
                            22974,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid334",
                            "height",
                            23974,
                            987,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid335",
                            "height",
                            24961,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid336",
                            "height",
                            25961,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid337",
                            "height",
                            26961,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid338",
                            "height",
                            27961,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid347",
                            "height",
                            28961,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid348",
                            "height",
                            29961,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid349",
                            "height",
                            30961,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid350",
                            "height",
                            31961,
                            987,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid351",
                            "height",
                            32948,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid352",
                            "height",
                            33948,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid353",
                            "height",
                            34948,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid354",
                            "height",
                            35948,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid27",
                            "height",
                            4000,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid33",
                            "height",
                            5000,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid37",
                            "height",
                            6000,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid86",
                            "height",
                            7000,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid88",
                            "height",
                            8000,
                            987,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid148",
                            "height",
                            8987,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid149",
                            "height",
                            9987,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid150",
                            "height",
                            10987,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid151",
                            "height",
                            11987,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid427",
                            "height",
                            12993,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid428",
                            "height",
                            13993,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid429",
                            "height",
                            14993,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid430",
                            "height",
                            15993,
                            987,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid431",
                            "height",
                            16980,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid432",
                            "height",
                            17980,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid433",
                            "height",
                            18980,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid434",
                            "height",
                            19980,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid443",
                            "height",
                            20980,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid444",
                            "height",
                            21980,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid445",
                            "height",
                            22980,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid446",
                            "height",
                            23980,
                            987,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid447",
                            "height",
                            24967,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid448",
                            "height",
                            25967,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid449",
                            "height",
                            26967,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid450",
                            "height",
                            27967,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid459",
                            "height",
                            28967,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid460",
                            "height",
                            29967,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid461",
                            "height",
                            30967,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid462",
                            "height",
                            31967,
                            987,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid463",
                            "height",
                            32954,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid464",
                            "height",
                            33954,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid465",
                            "height",
                            34954,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid466",
                            "height",
                            35954,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid28",
                            "width",
                            5000,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid34",
                            "width",
                            6000,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid40",
                            "width",
                            7000,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid81",
                            "width",
                            8000,
                            987,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid139",
                            "width",
                            8987,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid140",
                            "width",
                            9987,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid141",
                            "width",
                            10987,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid142",
                            "width",
                            11987,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid323",
                            "width",
                            12987,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid324",
                            "width",
                            13987,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid325",
                            "width",
                            14987,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid326",
                            "width",
                            15987,
                            987,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid327",
                            "width",
                            16974,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid328",
                            "width",
                            17974,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid329",
                            "width",
                            18974,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid330",
                            "width",
                            19974,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid339",
                            "width",
                            20974,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid340",
                            "width",
                            21974,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid341",
                            "width",
                            22974,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid342",
                            "width",
                            23974,
                            987,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid343",
                            "width",
                            24961,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid344",
                            "width",
                            25961,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid345",
                            "width",
                            26961,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid346",
                            "width",
                            27961,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid355",
                            "width",
                            28961,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid356",
                            "width",
                            29961,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid357",
                            "width",
                            30961,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid358",
                            "width",
                            31961,
                            987,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid359",
                            "width",
                            32948,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid360",
                            "width",
                            33948,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid361",
                            "width",
                            34948,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid362",
                            "width",
                            35948,
                            1000,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid31",
                            "height",
                            6000,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid84",
                            "height",
                            7000,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid158",
                            "height",
                            8000,
                            987,
                            "linear",
                            "${youtube-logo2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid163",
                            "height",
                            8987,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid164",
                            "height",
                            9987,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid165",
                            "height",
                            10987,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid166",
                            "height",
                            11987,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid363",
                            "height",
                            12993,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid364",
                            "height",
                            13993,
                            987,
                            "linear",
                            "${youtube-logo2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid365",
                            "height",
                            14980,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid366",
                            "height",
                            15980,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid367",
                            "height",
                            16980,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid368",
                            "height",
                            17980,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid375",
                            "height",
                            18980,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid376",
                            "height",
                            19980,
                            987,
                            "linear",
                            "${youtube-logo2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid377",
                            "height",
                            20967,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid378",
                            "height",
                            21967,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid379",
                            "height",
                            22967,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid380",
                            "height",
                            23967,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid387",
                            "height",
                            24967,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid388",
                            "height",
                            25967,
                            987,
                            "linear",
                            "${youtube-logo2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid389",
                            "height",
                            26954,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid390",
                            "height",
                            27954,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid391",
                            "height",
                            28954,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid392",
                            "height",
                            29954,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid399",
                            "height",
                            30954,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid400",
                            "height",
                            31954,
                            987,
                            "linear",
                            "${youtube-logo2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid401",
                            "height",
                            32941,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid402",
                            "height",
                            33941,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid403",
                            "height",
                            34941,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '33.33%',
                            '31.67%'
                        ],
                        [
                            "eid404",
                            "height",
                            35941,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '31.67%',
                            '33.33%'
                        ],
                        [
                            "eid6",
                            "opacity",
                            3000,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '0',
                            '1'
                        ],
                        [
                            "eid3",
                            "top",
                            0,
                            1250,
                            "linear",
                            "${text}",
                            '55%',
                            '5%'
                        ],
                        [
                            "eid5",
                            "opacity",
                            2010,
                            990,
                            "linear",
                            "${new-facebook-logo-2015-400x4002}",
                            '0',
                            '1'
                        ],
                        [
                            "eid1",
                            "opacity",
                            0,
                            1250,
                            "linear",
                            "${text}",
                            '0',
                            '1'
                        ],
                        [
                            "eid26",
                            "width",
                            4000,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid32",
                            "width",
                            5000,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid36",
                            "width",
                            6000,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid85",
                            "width",
                            7000,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid87",
                            "width",
                            8000,
                            987,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid152",
                            "width",
                            8987,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid153",
                            "width",
                            9987,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid154",
                            "width",
                            10987,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid155",
                            "width",
                            11987,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid435",
                            "width",
                            12993,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid436",
                            "width",
                            13993,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid437",
                            "width",
                            14993,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid438",
                            "width",
                            15993,
                            987,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid439",
                            "width",
                            16980,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid440",
                            "width",
                            17980,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid441",
                            "width",
                            18980,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid442",
                            "width",
                            19980,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid451",
                            "width",
                            20980,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid452",
                            "width",
                            21980,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid453",
                            "width",
                            22980,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid454",
                            "width",
                            23980,
                            987,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid455",
                            "width",
                            24967,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid456",
                            "width",
                            25967,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid457",
                            "width",
                            26967,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid458",
                            "width",
                            27967,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid467",
                            "width",
                            28967,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid468",
                            "width",
                            29967,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid469",
                            "width",
                            30967,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid470",
                            "width",
                            31967,
                            987,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid471",
                            "width",
                            32954,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid472",
                            "width",
                            33954,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid473",
                            "width",
                            34954,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid474",
                            "width",
                            35954,
                            1000,
                            "linear",
                            "${banner-com-o-logotipo-do-twitter2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid30",
                            "width",
                            6000,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid38",
                            "width",
                            7000,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid83",
                            "width",
                            8000,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid146",
                            "width",
                            9000,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid147",
                            "width",
                            10000,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid168",
                            "width",
                            11000,
                            987,
                            "linear",
                            "${youtube-logo2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid170",
                            "width",
                            11987,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid369",
                            "width",
                            12993,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid370",
                            "width",
                            13993,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid371",
                            "width",
                            14993,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid372",
                            "width",
                            15993,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid373",
                            "width",
                            16993,
                            987,
                            "linear",
                            "${youtube-logo2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid374",
                            "width",
                            17980,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid381",
                            "width",
                            18980,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid382",
                            "width",
                            19980,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid383",
                            "width",
                            20980,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid384",
                            "width",
                            21980,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid385",
                            "width",
                            22980,
                            987,
                            "linear",
                            "${youtube-logo2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid386",
                            "width",
                            23967,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid393",
                            "width",
                            24967,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid394",
                            "width",
                            25967,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid395",
                            "width",
                            26967,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid396",
                            "width",
                            27967,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid397",
                            "width",
                            28967,
                            987,
                            "linear",
                            "${youtube-logo2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid398",
                            "width",
                            29954,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid405",
                            "width",
                            30954,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid406",
                            "width",
                            31954,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid407",
                            "width",
                            32954,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid408",
                            "width",
                            33954,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '26.35%',
                            '27.32%'
                        ],
                        [
                            "eid409",
                            "width",
                            34954,
                            987,
                            "linear",
                            "${youtube-logo2}",
                            '27.32%',
                            '26.35%'
                        ],
                        [
                            "eid410",
                            "width",
                            35941,
                            1000,
                            "linear",
                            "${youtube-logo2}",
                            '26.35%',
                            '27.32%'
                        ]
                    ]
                }
            }
        };

    AdobeEdge.registerCompositionDefn(compId, symbols, fonts, scripts, resources, opts);

    if (!window.edge_authoring_mode) AdobeEdge.getComposition(compId).load("Untitled-2_edgeActions.js");
})("EDGE-481228510");
